name: "Checkout"
description: "Checkout the required shards & formabble repositories"
inputs:
  rust-toolchain-suffix:  # id of input
    required: false
    default: ''
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Import settings
      shell: bash
      run: |
        cat .config >> $GITHUB_ENV

    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: fragcolor-xyz/formabble
        token: ${{ inputs.github-token }}
        path: formabble
        ref: ${{ env.FBL_REF }}
        submodules: recursive
        fetch-depth: 1

    - name: Checkout public repository
      uses: actions/checkout@v3
      with:
        repository: fragcolor-xyz/shards
        token: ${{ inputs.github-token }}
        path: shards
        ref: ${{ env.SHARDS_REF }}
        submodules: recursive
        fetch-depth: 1
        
    - name: Set up rust
      shell: bash
      env:
        RUSTUP_USE_CURL: 1
      run: |
        RUSTUP_TOOLCHAIN=`cat shards/rust.version`${{ inputs.rust-toolchain-suffix }}
        echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
        rustup toolchain install $RUSTUP_TOOLCHAIN