name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout'
        required: true

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: fragcolor-xyz/formabble
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        path: formabble
        ref: ${{ github.event.inputs.tag }}
        submodules: recursive
        fetch-depth: 1

    - name: Checkout public repository
      uses: actions/checkout@v3
      with:
        repository: fragcolor-xyz/shards
        path: shards
        ref: ${{ github.event.inputs.tag }}
        submodules: recursive
        fetch-depth: 1

    - name: Set up rust
      shell: bash
      env:
        RUSTUP_USE_CURL: 1
      run: |
        RUSTUP_TOOLCHAIN=`cat shards/rust.version`-msvc
        echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
        rustup toolchain install $RUSTUP_TOOLCHAIN

    - name: Set up dev dependencies
      shell: bash
      run: |
        choco install -y --force --version=16.0.6 llvm
        choco install -y cmake ninja

    - name: Build
      env:
        RUST_BACKTRACE: full
      shell: bash
      run: |
        cd shards
        ./bootstrap
        cd ../formabble
        mkdir build
        cd build
        cmake -G Ninja \
          "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang.exe" \
          "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang++.exe" \
          "-DRUST_DEFAULT_TARGET_PATH=C:\shards-rust-target" \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        echo "Building shards"
        ninja fbl

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          formabble/build/fbl.exe
          formabble/build/fbl.pdb
          formabble/build/crsqlite.dll
          formabble/build/crsqlite.pdb
        token: ${{ secrets.GITHUB_TOKEN }}
